agent:
  type: ppo
  lr: 0.0003
  gamma: 0.99
  clip_epsilon: 0.2

environment:
  name: SolidityOptimizationEnv
  max_steps: 1000
  reward_scale: 1.0

training:
  num_episodes: 10000
  max_steps: 1000
  seed: 42
  save_interval: 10000
  eval_interval: 50

paths:
  log: ""
  checkpoints: python/solidity_rl/models/checkpoints
  results: python/solidity_rl/data/results/

hardware:
  use_cuda: true
  cuda_device: 0

misc:
  verbose: true
  render: false
